### ISSUE TITLE
Need to add a slider to the home page

### ISSUE THREAD

**Issue by Janith889** [Janith889/CatRescue#3]
Need to add a slider to the top of homepage that can handle 3,4 images

**Comment by PreetiBaskey** [comment]
hey @Janith889 , Basically, i can help you to make the app version of your website. If you interested, here is some of my work, if you like it, kindly accept my PR and assign me the Issue.

Login Page : https://user-images.githubusercontent.com/38905783/136938416-bf06e653-9d1a-4647-bd0a-31169f764cfe.jpg

Landing Page : https://user-images.githubusercontent.com/38905783/136938469-c5a04272-afe9-4c30-942b-f09eda4f17dc.jpg

Location Access Page : https://user-images.githubusercontent.com/38905783/136938580-da33c7d4-7ab3-4a80-a9ac-194f1b3edc32.jpg

Check In Page : https://user-images.githubusercontent.com/38905783/136938663-cd1d3e1f-306a-4fd0-b29c-3bc8c5417cda.jpg

Success Page : https://user-images.githubusercontent.com/38905783/136938703-f01f0c23-a19f-42bc-8379-77a95091b8eb.jpg

**Comment by Janith889** [comment]
Added by janith96
